[package]
name = "codemp-intellij"
version = "0.1.0"
edition = "2021"

[dependencies]
codemp = { git = "ssh://git@github.com/codewithotherpeopleandchangenamelater/codemp.git", tag = "v0.4.2" }
jni = "0.21.1"

[lib]
crate_type = ["cdylib"]
path = "src/main/rust/lib.rs"
